const pages = [
    { title: "He-Man and the Masters of the Universe", url: "MOTU.html",
    keywords: "Heman motu masters eternia 1983 1984 1985 skeletor filmation marvel mattel"
},
    { title: "G.I. Joe", url: "PAGES/GIJoe.html", keywords: "GIJoe yo joe duke scarlett snake cobra hasbro 1982 1983 1984 1985 1986 1987 1988 1989 Sunbow Marvel" },
    { title: "ThunderCats", url: "PAGES/ThunderCats.html", keywords: "thunder cats thundercats mumm-ra lion-o tigra cheetara thundera panthro 1985 1986 1987 1988 1989 rankin bass ljn star"},
    { title: "Voltron", url: "PAGES/voltron.html" },
    { title: "Beverly Hills Teens", url: "PAGES/Beverly Hills Teens.html" },
    { title: "Bionic Six", url: "PAGES/Bionic6.html" },
    { title: "Blackstar", url: "PAGES/Blackstar.html" },
    { title: "BraveStarr", url: "PAGES/BraveStarr.html" },
    { title: "The Centurions", url: "PAGES/Centurions.html" },
    { title: "Defenders of the Earth", url: "PAGES/DefendersoftheEarth.html" },
    { title: "Denver the Last Dinosaur", url: "PAGES/Denver the Last Dinosaur.html" },
    { title: "Dino-Riders", url: "PAGES/DinoRiders.html" },
    { title: "Dinosaucers", url: "PAGES/Dinosaucers.html" },
    { title: "Disney's DuckTales", url: "PAGES/DuckTales.html" },
    { title: "Dungeons & Dragons", url: "PAGES/Dungeons&Dragons.html" },
    { title: "Filmation's Ghostbusters", url: "PAGES/FilmationsGhostbusters.html" },
    { title: "Heathcliff and the Catillac Cats", url: "PAGES/Heathcliff.html" },
    { title: "Hulk Hogan's Rock N' Wrestling", url: "PAGES/HulkHoganRNW.html" },
    { title: "Inspector Gadget", url: "PAGES/InspectorGadget.html" },
    { title: "Jem and the Holograms", url: "PAGES/Jem.html" },
    { title: "My Little Pony N' Friends", url: "PAGES/My Little Pony N' Friends.html" },
    { title: "Pole Position", url: "PAGES/PolePosition.html" },
    { title: "Rainbow Brite", url: "PAGES/Rainbow Brite.html" },
    { title: "Sectaurs: Warriors of Symbion", url: "PAGES/Sectaurs.html" },
    { title: "SilverHawks", url: "PAGES/SilverHawks.html" },
    { title: "M.A.S.K.", url: "PAGES/mask.html" }
];

