const pages = [
    { title: "He-Man and the Masters of the Universe", url: "MOTU.html",
    keywords: "Heman motu masters eternia 1983 1984 1985 skeletor filmation marvel mattel"
},
    { title: "G.I. Joe", url: "PAGES/GIJoe.html", keywords: "GIJoe yo joe duke scarlett snake cobra hasbro 1982 1983 1984 1985 1986 1987 1988 1989 Sunbow Marvel" },
    { title: "ThunderCats", url: "ThunderCats.html", keywords: "thunder cats thundercats mumm-ra lion-o tigra cheetara thundera panthro 1985 1986 1987 1988 1989 rankin bass ljn star"},
    { title: "Voltron", url: "voltron.html" },
    { title: "Beverly Hills Teens", url: "Beverly Hills Teens.html" },
    { title: "Bionic Six", url: "Bionic6.html" },
    { title: "Blackstar", url: "Blackstar.html" },
    { title: "BraveStarr", url: "BraveStarr.html" },
    { title: "The Centurions", url: "Centurions.html" },
    { title: "Defenders of the Earth", url: "DefendersoftheEarth.html" },
    { title: "Denver the Last Dinosaur", url: "Denver the Last Dinosaur.html" },
    { title: "Dino-Riders", url: "DinoRiders.html" },
    { title: "Dinosaucers", url: "Dinosaucers.html" },
    { title: "Disney's DuckTales", url: "DuckTales.html" },
    { title: "Dungeons & Dragons", url: "Dungeons&Dragons.html" },
    { title: "Filmation's Ghostbusters", url: "FilmationsGhostbusters.html" },
    { title: "Heathcliff and the Catillac Cats", url: "Heathcliff.html" },
    { title: "Hulk Hogan's Rock N' Wrestling", url: "HulkHoganRNW.html" },
    { title: "Inspector Gadget", url: "InspectorGadget.html" },
    { title: "Jem and the Holograms", url: "Jem.html" },
    { title: "My Little Pony N' Friends", url: "My Little Pony N' Friends.html" },
    { title: "Pole Position", url: "PolePosition.html" },
    { title: "Rainbow Brite", url: "Rainbow Brite.html" },
    { title: "Sectaurs: Warriors of Symbion", url: "Sectaurs.html" },
    { title: "SilverHawks", url: "SilverHawks.html" },
    { title: "M.A.S.K.", url: "mask.html" }
];

